//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRTesting : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean BodyCalibrate
        {
            get
            {
                return SteamVR_Actions.vRTesting_BodyCalibrate;
            }
        }
        
        public virtual SteamVR_Action_Boolean DistanceTracker
        {
            get
            {
                return SteamVR_Actions.vRTesting_DistanceTracker;
            }
        }
        
        public virtual SteamVR_Action_Boolean RoomGenerate
        {
            get
            {
                return SteamVR_Actions.vRTesting_RoomGenerate;
            }
        }
    }
}
